name: macOS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  macos:
    name: macOS
    runs-on: macos-11
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Install ninja
        run: brew install ninja

      - name: CMake configure -- Release
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DLT_BUILD_BENCHMARK=OFF

      - name: CMake build -- Release
        run: cmake --build build --config "Release"

      - name: CTest -- Release
        run: ctest --test-dir build -C Release
